### PR TITLE
feature/startscripts

### PR DESCRIPTION
**Pull request by cs8898**
Added 2 Scripts to simplify a basic venv installation

without the tools needed for WebPage PDF Generation

## install.sh
* Create venv (./env)
* source venv (./env)
* Install Requirements

## launch.sh
* Extract current script Path ([StackOverflow](https://stackoverflow.com/questions/59895/how-to-get-the-source-directory-of-a-bash-script-from-within-the-script-itself))
* cd to Script Path
* source env (./env)
* launch rema.py

I use the launch script as a symlink to my bin folder

### CODE REVIEW

**Comment by peerdavid** [comment]
Thx for both scripts. Is there a reason to use "pip3" in line 6 and "pip" in line 7 (install.sh)? If not I would suggest to also use "pip3" in line 7?

I will also update the wiki accordingly when the pull request is merged :)

Thanks, 
David

**Comment by cs8898** [comment]
Great Tool :+1:
definitly better than using a WindowsVM to Extract file while im on my computer...

I changed 7 to use also `pip3`

Regards,
Chris

**Comment by peerdavid** [comment]
The pull request is merged, the [wiki](https://github.com/peerdavid/remapy/wiki/Install) is updated accordingly and I also updated the .desktop file to use the launch script and not the python script directly.

Thanks again,
David

**Comment by cs8898** [comment]
Great ;)

You'r welcome

**Pull request merged**
